title: Odinakachi Nnajindum
logo: /assets/img/my_photo.jpg
description: Aspiring Data Scientist | Python | SQL | Machine Learning Enthusiast
url: https://Jindum.github.io
show_downloads: true
resume: /assets/Odinakachi_Resume.pdf
theme: jekyll-theme-minimal
